#%RAML 1.0
title: CommisionAPI
version: 1.0
description:  to utilize the backend MDM system to store all future Sales data

types:
  salesdataType: !include /exchange_modules/03173809-46cc-4abd-b798-3eb63a49ba7f/salesdata/1.0.4/salesdata.raml
traits: 
  errorresponse: !include exchange_modules/03173809-46cc-4abd-b798-3eb63a49ba7f/errorresponse/1.0.0/errorresponse.raml
securitySchemes:
  Oauth: !include exchange_modules/03173809-46cc-4abd-b798-3eb63a49ba7f/oauth20/1.0.0/oauth20.raml



securedBy: [Oauth]
/commission:
  is: [errorresponse]
  displayName: Calculate Commission
  description: commission is calculated and stored in a separate commission table for each sales order.
  post:
    displayName: Add record 
    body:
      application/json:
        type: salesdataType
        example: !include salesdataexample.raml
    responses:
      201:
        body:
          application/json:
            example:
              value:  Record Added
    